const actionType = {
  "CAN_CASTLE" : "CAN_CASTLE",
  "STALEMATE": "STALEMATE",
  "CLEAR_CANDIDATE_MOVES":"CLEAR_CANDIDATE_MOVES",
  "NEW_MOVE" : "NEW_MOVE",   
  "GENERATE_CANDIDATE_MOVES" : "GENERATE_CANDIDATE_MOVES",
  "PROMOTION_OPEN": "PROMOTION_OPEN",
  "PROMOTION_CLOSE": "PROMOTION_CLOSE",
  "NEW_GAME": "NEW_GAME",
  "INSUFFICIENT":"INSUFFICIENT",
  "CHECKMATE": "CHECKMATE"
  
}

export default actionType;